// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakersApp.Data;

namespace SneakersApp.Data.Migrations
{
    [DbContext(typeof(SneakersAppDbContext))]
    [Migration("20190427232023_Collection model")]
    partial class Collectionmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SneakersApp.Data.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SneakersApp.Data.Models.Shoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollectionID");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CollectionID");

                    b.ToTable("Shoes");
                });

            modelBuilder.Entity("SneakersApp.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("ShoesId");

                    b.HasKey("Id");

                    b.HasIndex("ShoesId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SneakersApp.Data.Models.Shoes", b =>
                {
                    b.HasOne("SneakersApp.Data.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionID");
                });

            modelBuilder.Entity("SneakersApp.Data.Models.Tag", b =>
                {
                    b.HasOne("SneakersApp.Data.Models.Shoes")
                        .WithMany("Tags")
                        .HasForeignKey("ShoesId");
                });
#pragma warning restore 612, 618
        }
    }
}
